name: todo_riverpod_sqflite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter_riverpod: ^2.4.10
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^13.2.0
  google_fonts: ^6.2.0
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.3.2 
  path_provider: ^2.1.2
  sqflite_common_ffi: ^2.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  

flutter:
  uses-material-design: true
